#Stand: 01.07.2026 
# https://docs.python.org/3/library/configparser.html
# In Python-Skript
#   from configparser import ConfigParser, ExtendedInterpolation
#   config = ConfigParser(interpolation=ExtendedInterpolation())
#   config.read('<Dateiname der Date wie config.ini>')

[DEFAULT]
prefix = D:\git\GSpp
#prefix =  C:\Python\GSpp
implementation_file_generated = 260608
#kontakt = 

# commits: 260206 260217 260305 260316 260402 260420 260529 260701 260703
commit = 260703

# Für Vergleiche
commit_a = 260701
commit_b = 260703

[orte]
#spielwiese
#path_catalog_xlsx = ${prefix}\daten\spielwiese\catalog_${commit}.xlsx

#path_logo = ${prefix}\daten\quellen\Logo.jpg

path_catalog = ${prefix}\daten\catalog_github_commit_${commit}\quellen\catalog_${commit}.json
path_catalog_flattened = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\catalog_${commit}_flattened.json
path_catalog_flattened_reversed = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\catalog_${commit}_flattened_reversed.json
path_catalog_xlsx = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\catalog_${commit}.xlsx
path_control_attributes = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\control_${commit}_attributes.json
path_control_attributes_update = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\control_${commit}_attributes_update.json


# für Implementierungen zu einem catalog commit
path_catalog_implementations = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\catalog_${commit}_implementations.json

#github
path_github_bsi_gspp_catalog = https://github.com/BSI-Bund/Stand-der-Technik-Bibliothek/tree/main/Anwenderkataloge
path_github_bsi_gspp_implementierungen = https://github.com/BSI-Bund/Stand-der-Technik-Bibliothek/tree/main/Implementierungsbeschreibungen
path_github_vorgebirge_gspp = https://github.com/Vorgebirge/Grundschutz-Plus-Plus
path_github_bsi_gspp_namespace_definitionen = https://github.com/BSI-Bund/Stand-der-Technik-Bibliothek/tree/main/Dokumentation/namespaces

# Für Vergleiche
path_catalog_a = ${prefix}\daten\catalog_github_commit_${commit_a}\quellen\catalog_${commit_a}.json
path_catalog_flattened_a = ${prefix}\daten\catalog_github_commit_${commit_a}\ergebnisse\catalog_${commit_a}_flattened.json
path_catalog_flattened_reversed_a = ${prefix}\daten\catalog_github_commit_${commit_a}\ergebnisse\catalog_${commit_a}_flattened_reversed.json
path_control_attributes_a = ${prefix}\daten\catalog_github_commit_${commit_a}\ergebnisse\control_${commit_a}_attributes.json

path_catalog_b = ${prefix}\daten\catalog_github_commit_${commit_b}\quellen\catalog_${commit_b}.json
path_catalog_flattened_b = ${prefix}\daten\catalog_github_commit_${commit_b}\ergebnisse\catalog_${commit_b}_flattened.json
path_catalog_flattened_reversed_b = ${prefix}\daten\catalog_github_commit_${commit_b}\ergebnisse\catalog_${commit_b}_flattened_reversed.json
path_control_attributes_b = ${prefix}\daten\catalog_github_commit_${commit_b}\ergebnisse\control_${commit_b}_attributes.json

path_diff_report = ${prefix}\daten\diff_reports\diff-report-gs++-${commit_a}-${commit_b}.md
path_diff_report_uuid_centric = ${prefix}\daten\spielwiese\diff-report-uuid-centric-gs++-${commit_a}-${commit_b}.md

path_implementations = ${prefix}\daten\implementations\implementations-${implementation_file_generated}.json

# --------------------------------------- Implementierung - Komponenten -------------------------------------------

[implementierungen]
# die Bezeichner der nachfolgenden sections
komponenten = aws_iam, aws_security_hub, netzarchitektur, passwortrichtlinie, wlan

[aws_iam]
typ = implementierungen_komponente
name = AWS IAM
# commits 260420
commit = 260420
commit_a = 260420
#commit_b = 
source = aws_iam-component_definition.json
prefix_komponente = ${prefix}\daten\quellen\bsi-komponenten\aws-beispiel-components\aws_iam-component_definition_
path = ${aws_iam:prefix_komponente}${aws_iam:commit}.json
path_a = ${aws_iam:prefix_komponente}${aws_iam:commit_a}.json
#path_b = ${aws_iam:prefix_komponente}${aws_iam:commit_b}.json

[aws_security_hub]
typ = implementierungen_komponente
name = AWS Security Hub
# commits 260420
commit = 260420
commit_a = 260420
#commit_b = 
source = aws_security_hub-component_definition.json
prefix_komponente = ${prefix}\daten\quellen\bsi-komponenten\aws-beispiel-components\aws_security_hub-component_definition_
path = ${aws_security_hub:prefix_komponente}${aws_security_hub:commit}.json
path_a = ${aws_security_hub:prefix_komponente}${aws_security_hub:commit_a}.json
#path_b = ${aws_security_hub:prefix_komponente}${aws_security_hub:commit_b}.json

[netzarchitektur]
typ = implementierungen_komponente
name = Netzarchitektur
# commits 260420
commit = 260420
commit_a = 260420
#commit_b = 
source = Netzarchitektur-component_definition.json
prefix_komponente = ${prefix}\daten\quellen\bsi-komponenten\netzarchitektur\netzarchitektur_component_definition_
path = ${netzarchitektur:prefix_komponente}${netzarchitektur:commit}.json
path_a = ${netzarchitektur:prefix_komponente}${netzarchitektur:commit_a}.json
#path_b = ${netzarchitektur:prefix_komponente}${netzarchitektur:commit_b}.json

[passwortrichtlinie]
typ = implementierungen_komponente
name = Passwortrichtlinie
# commits 260420 260608
commit = 260608
commit_a = 260420
commit_b = 260608 
source = Passwortrichtlinie-component_definition.json
prefix_komponente = ${prefix}\daten\quellen\bsi-komponenten\passwortrichtlinie\passwortrichtlinie_component_definition_
path = ${passwortrichtlinie:prefix_komponente}${passwortrichtlinie:commit}.json
path_a = ${passwortrichtlinie:prefix_komponente}${passwortrichtlinie:commit_a}.json
path_b = ${passwortrichtlinie:prefix_komponente}${passwortrichtlinie:commit_b}.json


[wlan]
typ = implementierungen_komponente
name = WLAN
# commits 260420
commit = 260420
commit_a = 260420
#commit_b = 
source = WLAN-component_definition.json
prefix_komponente = ${prefix}\daten\quellen\bsi-komponenten\wlan\wlan_component_definition_
path = ${wlan:prefix_komponente}${wlan:commit}.json
path_a = ${wlan:prefix_komponente}${wlan:commit_a}.json
#path_b = ${wlan:prefix_komponente}${wlan:commit_b}.json

#-------------------------------------------- Ende  Implementierung - Komponenten --------------------------------------------

[control_attributes]
#links Feld in json, rechts Feld in xlsx, mindestens für Delta-Bericht, ...
action_word = Handlungswort
alt-identifier = UUID
authenticity = Authentizität
availability = Verfügbarkeit
class = Klasse
confidentiality = Vertraulichkeit 
documentation = Dokumentation
# ergebnis = Ergebnis, ab 16.03.26: result
effort_level = Aufwand
guidance = Hinweis
# handlungsworte = Handlungswort, seit 16.03.2026: action_word
id = ID
integrity = Integrität
# modalverb = Modalverb, seit 16.03.2026: modal_verb
modal_verb = Modalverb
params = Parameter
# präzisierung = Präzisierung, seit 16.03.2026: result_specification
praktik = Praktik
praktik_thema = Thema
praktik_typ = Praktik_Typ
prose = Text
related = Verwandte
required = Abhängigkeit
result = Ergebnis 
result_specification = Präzisierung
sec_level = Sicherheitsniveau
tags = Tags
# target_objects = Zielobjekte, seit 16.03.2026: target_object_categories 
target_object_categories = Zielobjekte
threats = Elementare Gefährdung
title = Titel
verbesserung = Verbesserung

[praktik_types]
GC = Methodik
PERF = Methodik
RISK = Methodik
STM = Methodik
UMS = Methodik
VRB = Methodik
ARCH = Technisch
BER = Technisch
DET = Technisch
DEV = Technisch
KONF = Technisch
REA = Technisch
NOT = Technisch
ASST = Organisatorisch
BES = Organisatorisch
DLS = Organisatorisch
GEB = Organisatorisch
PERS = Organisatorisch
SENS = Organisatorisch
TEST = Organisatorisch