#Stand: 25.05.2026 
# https://docs.python.org/3/library/configparser.html
# In Python-Skript
#   from configparser import ConfigParser, ExtendedInterpolation
#   config = ConfigParser(interpolation=ExtendedInterpolation())
#   config.read('<Dateiname wie spielwiese.ini>')

[DEFAULT]
prefix = D:\git\GSpp
#prefix =  C:\Python\GSpp
implementation_file_generated = 260525
#kontakt = 

#commit = 260206
#commit = 260217
#commit = 260305
#commit = 260316
#commit = 260402
commit = 260420

# Für Vergleiche
#commit_a = 260206
#commit_a = 260217
#commit_a = 260305
#commit_a = 260316
commit_a = 260402

#commit_b = 260217
#commit_b = 260305
#commit_b = 260316
#commit_b = 260402
commit_b = 260420

[orte]
#spielwiese
#path_catalog_xlsx = ${prefix}\daten\spielwiese\catalog_${commit}.xlsx

#path_logo = ${prefix}\daten\quellen\Logo.jpg

path_catalog = ${prefix}\daten\catalog_github_commit_${commit}\quellen\catalog_${commit}.json
path_catalog_flattened = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\catalog_${commit}_flattened.json
path_catalog_flattened_reversed = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\catalog_${commit}_flattened_reversed.json
path_catalog_xlsx = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\catalog_${commit}.xlsx
path_control_attributes = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\control_${commit}_attributes.json
path_control_attributes_update = ${prefix}\daten\catalog_github_commit_${commit}\ergebnisse\control_${commit}_attributes_update.json

#github
path_github_bsi_gspp_catalog = https://github.com/BSI-Bund/Stand-der-Technik-Bibliothek/tree/main/Anwenderkataloge
path_github_bsi_gspp_implementierungen = https://github.com/BSI-Bund/Stand-der-Technik-Bibliothek/tree/main/Implementierungsbeschreibungen
path_github_vorgebirge_gspp = https://github.com/Vorgebirge/Grundschutz-Plus-Plus

# Für Vergleiche
path_catalog_a = ${prefix}\daten\catalog_github_commit_${commit_a}\quellen\catalog_${commit_a}.json
path_catalog_flattened_a = ${prefix}\daten\catalog_github_commit_${commit_a}\ergebnisse\catalog_${commit_a}_flattened.json
path_catalog_flattened_reversed_a = ${prefix}\daten\catalog_github_commit_${commit_a}\ergebnisse\catalog_${commit_a}_flattened_reversed.json
path_control_attributes_a = ${prefix}\daten\catalog_github_commit_${commit_a}\ergebnisse\control_${commit_a}_attributes.json

path_catalog_b = ${prefix}\daten\catalog_github_commit_${commit_b}\quellen\catalog_${commit_b}.json
path_catalog_flattened_b = ${prefix}\daten\catalog_github_commit_${commit_b}\ergebnisse\catalog_${commit_b}_flattened.json
path_catalog_flattened_reversed_b = ${prefix}\daten\catalog_github_commit_${commit_b}\ergebnisse\catalog_${commit_b}_flattened_reversed.json
path_control_attributes_b = ${prefix}\daten\catalog_github_commit_${commit_b}\ergebnisse\control_${commit_b}_attributes.json

path_diff_report = ${prefix}\daten\diff_reports\diff-report-gs++-${commit_a}-${commit_b}.md

path_implementations = ${prefix}\daten\implementations\implementations-${implementation_file_generated}.json

# --------------------------------------- Implementierung - Komponenten -------------------------------------------

[implementierungen]
# die Bezeichner der nachfolgenden sections
komponenten = aws_iam, aws_security_hub, netzarchitektur, passwortrichtlinie, wlan

[aws_iam]
name = AWS IAM
commit = 260420
source = aws_iam-component_definition.json
path = ${prefix}\daten\quellen\bsi-komponenten\aws-beispiel-components\aws_iam-component_definition_${aws_iam:commit}.json

[aws_security_hub]
name = AWS Security Hub
commit = 260420
source = aws_security_hub-component_definition.json
path = ${prefix}\daten\quellen\bsi-komponenten\aws-beispiel-components\aws_security_hub-component_definition_${aws_security_hub:commit}.json

[netzarchitektur]
name = Netzarchitektur
commit = 260420
source = Netzarchitektur-component_definition.json
path = ${prefix}\daten\quellen\bsi-komponenten\netzarchitektur\netzarchitektur_component_definition_${netzarchitektur:commit}.json

[passwortrichtlinie]
name = Passwortrichtlinie
commit = 260420
source = Passwortrichtlinie-component_definition.json
path = ${prefix}\daten\quellen\bsi-komponenten\passwortrichtlinie\passwortrichtlinie_component_definition_${passwortrichtlinie:commit}.json

[wlan]
name = WLAN
commit = 260420
source = WLAN-component_definition.json
path = ${prefix}\daten\quellen\bsi-komponenten\wlan\wlan_component_definition_${wlan:commit}.json

#-------------------------------------------- Ende  Implementierung - Komponenten --------------------------------------------

[control_attributes]
#links Feld in json, rechts Feld in xlsx, mindestens für Delta-Bericht, ...
action_word = Handlungswort
alt-identifier = UUID
class = Klasse
documentation = Dokumentation
# ergebnis = Ergebnis, ab 16.03.26: result
effort_level = Aufwand
guidance = Hinweis
# handlungsworte = Handlungswort, seit 16.03.2026: action_word
id = ID
# modalverb = Modalverb, seit 16.03.2026: modal_verb
modal_verb = Modalverb
params = Parameter
# präzisierung = Präzisierung, seit 16.03.2026: result_specification
praktik = Praktik
praktik_thema = Thema
praktik_typ = Praktik_Typ
prose = Text
related = Verwandte
required = Abhängigkeit
result = Ergebnis 
result_specification = Präzisierung
sec_level = Sicherheitsniveau
tags = Tags
# target_objects = Zielobjekte, seit 16.03.2026: target_object_categories 
target_object_categories = Zielobjekte
title = Titel
verbesserung = Verbesserung

[praktik_types]
GC = Methodik
PERF = Methodik
RISK = Methodik
STM = Methodik
UMS = Methodik
VRB = Methodik
ARCH = Technisch
BER = Technisch
DET = Technisch
DEV = Technisch
KONF = Technisch
REA = Technisch
NOT = Technisch
ASST = Organisatorisch
BES = Organisatorisch
DLS = Organisatorisch
GEB = Organisatorisch
PERS = Organisatorisch
SENS = Organisatorisch
TEST = Organisatorisch