#Stand: 01.05.2026 

[daten]
datum_erstellung_xlsx = 260501
kontakt = stephan.huettinger@web.de

[orte]
prefix = D:\git\GSpp
#prefix =  C:\Python\GSpp

#commit = 260206
#commit = 260217
#commit = 260305
#commit = 260316
#commit = 260402
commit = 260420
path_catalog = %(prefix)s\daten\catalog_github_commit_%(commit)s\quellen\catalog_%(commit)s.json
path_catalog_flattened = %(prefix)s\daten\catalog_github_commit_%(commit)s\ergebnisse\catalog_%(commit)s_flattened.json
path_catalog_flattened_reversed = %(prefix)s\daten\catalog_github_commit_%(commit)s\ergebnisse\catalog_%(commit)s_flattened_reversed.json
path_catalog_xlsx = %(prefix)s\daten\catalog_github_commit_%(commit)s\ergebnisse\catalog_%(commit)s.xlsx
path_control_attributes = %(prefix)s\daten\catalog_github_commit_%(commit)s\ergebnisse\control_%(commit)s_attributes.json
path_control_attributes_update = %(prefix)s\daten\catalog_github_commit_%(commit)s\ergebnisse\control_%(commit)s_attributes_update.json
#path_logo = %(prefix)s\daten\quellen\Logo.jpg

# Für Vergleiche
#commit_a = 260206
#commit_a = 260217
#commit_a = 260305
#commit_a = 260316
commit_a = 260402
path_catalog_a = %(prefix)s\daten\catalog_github_commit_%(commit_a)s\quellen\catalog_%(commit_a)s.json
path_catalog_flattened_a = %(prefix)s\daten\catalog_github_commit_%(commit_a)s\ergebnisse\catalog_%(commit_a)s_flattened.json
path_catalog_flattened_reversed_a = %(prefix)s\daten\catalog_github_commit_%(commit_a)s\ergebnisse\catalog_%(commit_a)s_flattened_reversed.json
path_control_attributes_a = %(prefix)s\daten\catalog_github_commit_%(commit_a)s\ergebnisse\control_%(commit_a)s_attributes.json

# commit_b = 260217
#commit_b = 260305
#commit_b = 260316
#commit_b = 260402
commit_b = 260420
path_catalog_b = %(prefix)s\daten\catalog_github_commit_%(commit_b)s\quellen\catalog_%(commit_b)s.json
path_catalog_flattened_b = %(prefix)s\daten\catalog_github_commit_%(commit_b)s\ergebnisse\catalog_%(commit_b)s_flattened.json
path_catalog_flattened_reversed_b = %(prefix)s\daten\catalog_github_commit_%(commit_b)s\ergebnisse\catalog_%(commit_b)s_flattened_reversed.json
path_control_attributes_b = %(prefix)s\daten\catalog_github_commit_%(commit_b)s\ergebnisse\control_%(commit_b)s_attributes.json

path_diff_report = %(prefix)s\daten\diff_reports\diff-report-gs++-%(commit_a)s-%(commit_b)s.md

[control_attributes]
#links Feld in json, rechts Feld in xlsx, mindestens für Delta-Bericht, ...
action_word = Handlungswort
alt-identifier = UUID
class = Klasse
documentation = Dokumentation
# ergebnis = Ergebnis, ab 16.03.26: result
effort_level = Aufwand
guidance = Hinweis
# handlungsworte = Handlungswort, seit 16.03.2026: action_word
id = ID
# modalverb = Modalverb, seit 16.03.2026: modal_verb
modal_verb = Modalverb
params = Parameter
# präzisierung = Präzisierung, seit 16.03.2026: result_specification
praktik = Praktik
praktik_thema = Thema
praktik_typ = Praktik_Typ
prose = Text
related = Verwandte
required = Abhängigkeit
result = Ergebnis 
result_specification = Präzisierung
sec_level = Sicherheitsniveau
tags = Tags
# target_objects = Zielobjekte, seit 16.03.2026: target_object_categories 
target_object_categories = Zielobjekte
title = Titel
verbesserung = Verbesserung

[praktik_types]
GC = Methodik
PERF = Methodik
RISK = Methodik
STM = Methodik
UMS = Methodik
VRB = Methodik
ARCH = Technisch
BER = Technisch
DET = Technisch
DEV = Technisch
KONF = Technisch
REA = Technisch
NOT = Technisch
ASST = Organisatorisch
BES = Organisatorisch
DLS = Organisatorisch
GEB = Organisatorisch
PERS = Organisatorisch
SENS = Organisatorisch
TEST = Organisatorisch